---
# tasks file for lbweb
- name: install webserver
  package:
       name: "httpd"
       state: present
 
- name: copy webpages
  template:
     src: "index.html"
     dest: "/var/www/html/"  
- name: service start
  service:
      name: "httpd"
      state: started
